### ISSUE TITLE
MATLAB submission files can only have names that work as external function file's names.

### ISSUE THREAD

**Issue by aksholokhov** [aksholokhov/gspack#7]
In other words, it can be "solution.m" but it can not be "solution (1).m". Right now, if you submit the latter, gspack says "can't find 'solution'", which is confusing. Having a function that checks the names of submitted files and outputs a clear error message when the name is unacceptable would be very helpful for students. Otherwise, we should at least explain the naming requirements in the tutorial.

**Comment by amathsys** [comment]
Fixed. Addressed in [this PR](https://github.com/aksholokhov/gspack/pull/9).
